language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"  # current default Python on Travis CI
  - "3.7"
  - "3.8.3"
  - "3.8-dev"

jobs:
  allow_failures:
    - python: 3.8-dev
  # Allow marking as finished before non-required jobs complete
  fast_finish: true

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest -s -vvv