#!/bin/bash

# Job name:
#SBATCH --job-name=nimbus
#
# Project:
#SBATCH --account=nn9284k
#
# Wall clock limit:
#SBATCH --time=15:00:00
#
# Max memory usage:
# SBATCH --mem-per-cpu=10G --partition=hugemem
#SBATCH --mem-per-cpu=3936M 


# Set nodes and tasks
# Number of nodes                                                                   
#SBATCH --nodes=1                                                                                                                                                   
# Number of tasks on each node (number of tasks = number of MPI ranks)                                              
#SBATCH --ntasks-per-node=4



##
## Set up job environment
##
source /cluster/bin/jobsetup
set -o errexit # exit on errors


## Load required modules
module purge
module load python2/2.7.10.gnu
#module load openmpi.intel/1.10.2
# What modules do we have?
module list

## Make sure result files are copied at end

##
## Do some work:
##
#cp -r $HOME $SCRATCH
#cd $SCRATCH/Gaussian_oranges
#mpirun python DGP_parallel_oranges.py
STRING="Starting the Python program run_nimbus.py"
echo $STRING
/usr/bin/time python run_nimbus.py

STRING2="Finished run_nimbus.py."
echo $STRING2

## Clean up
#cd $SCRATCH
#tar -cf slhaball.tar run